"""added added_by field

Revision ID: 1b4e9b3a2269
Revises: 
Create Date: 2023-05-20 19:35:22.776794

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '1b4e9b3a2269'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opinion', sa.Column('added_by', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('opinion', 'added_by')
    # ### end Alembic commands ###
